print("hello word!")
print("hello word!")
# adding comment in between......///////////...........///
# this mean it cant be read by python compailer
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
print("hello word!")
